services:
  foundry:
    image: felddy/foundryvtt:release
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ~/foundry/data:/data
      - ../:/data/Data/modules/token-action-hud-tor2e
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD:-test}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME:-test}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY:-test}
    ports:
      - "30000:30000"